# Generated by Django 4.2.27 on 2026-01-30 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=120)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "current_mode",
                    models.CharField(
                        choices=[
                            ("listening", "listening"),
                            ("reflective", "reflective"),
                            ("spiritual_awareness", "spiritual_awareness"),
                            ("biblical", "biblical"),
                        ],
                        default="listening",
                        max_length=32,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VirtualFriend",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("name", models.CharField(default="Amigo Bíblico", max_length=48)),
                (
                    "persona",
                    models.TextField(
                        default="Amigo bíblico, acolhedor, pastoral, baseado em Escrituras."
                    ),
                ),
                ("tone", models.CharField(default="carinhoso", max_length=32)),
                ("age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("background", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_friends",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSpiritualProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "preferred_translation",
                    models.CharField(default="NVI", max_length=32),
                ),
                (
                    "doctrine_profile",
                    models.CharField(
                        choices=[
                            ("generic", "Cristão genérico"),
                            ("evangelical", "Evangélico"),
                            ("catholic", "Católico"),
                            ("custom", "Custom"),
                        ],
                        default="generic",
                        max_length=32,
                    ),
                ),
                ("onboarding_answers", models.JSONField(blank=True, default=dict)),
                ("allowed_topics", models.JSONField(blank=True, default=list)),
                ("blocked_topics", models.JSONField(blank=True, default=list)),
                ("extracted_profile", models.JSONField(default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spiritual_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReadingPlan",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("days", models.PositiveSmallIntegerField(default=7)),
                ("plan", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_plans",
                        to="core.virtualfriend",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrayerRequest",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("details", models.TextField(blank=True, default="")),
                ("is_answered", models.BooleanField(default=False)),
                ("answered_notes", models.TextField(blank=True, default="")),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prayer_requests",
                        to="core.virtualfriend",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                            ("tool", "Tool"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.conversation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FriendMemory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("episodic", "Episodic"),
                            ("semantic", "Semantic"),
                            ("prayer", "Prayer"),
                            ("verse", "Verse"),
                            ("plan", "Plan"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=128)),
                ("value", models.TextField()),
                (
                    "confidence",
                    models.DecimalField(decimal_places=2, default=0.8, max_digits=3),
                ),
                ("source", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to="core.virtualfriend",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="conversation",
            name="friend",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="core.virtualfriend",
            ),
        ),
        migrations.AddIndex(
            model_name="virtualfriend",
            index=models.Index(
                fields=["owner", "is_active", "created_at"],
                name="core_virtua_owner_i_d569d7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="readingplan",
            index=models.Index(
                fields=["friend", "is_active", "created_at"],
                name="core_readin_friend__3e1e9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prayerrequest",
            index=models.Index(
                fields=["friend", "is_answered", "created_at"],
                name="core_prayer_friend__e87453_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="core_messag_convers_d2b392_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "role", "created_at"],
                name="core_messag_convers_3fd6e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="friendmemory",
            index=models.Index(
                fields=["friend", "kind", "is_active"],
                name="core_friend_friend__0ecf8d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="friendmemory",
            index=models.Index(
                fields=["friend", "key"], name="core_friend_friend__ee33a4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="friendmemory",
            unique_together={("friend", "kind", "key")},
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["friend", "created_at"], name="core_conver_friend__7bd9d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["friend", "is_closed"], name="core_conver_friend__a1876b_idx"
            ),
        ),
    ]
