# Generated by Django 4.2.27 on 2026-02-04 21:20

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_user_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Telegram user ID (unique identifier from Telegram)",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User's name from Telegram (first name or full name)",
                        max_length=255,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="User's phone number (if shared)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "inferred_gender",
                    models.CharField(
                        blank=True,
                        help_text="Gender inferred from name (male/female/unknown)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "prompt_theme",
                    models.CharField(
                        blank=True,
                        help_text="Active thematic prompt id to apply to this user's conversation",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "pending_reset_confirmation",
                    models.BooleanField(
                        default=False,
                        help_text="True if user has initiated /reset and is awaiting confirmation",
                    ),
                ),
                (
                    "reset_confirmation_timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when /reset was initiated (expires after timeout)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RagChunk",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "source",
                    models.CharField(
                        db_index=True,
                        help_text="Source document identifier (e.g., filename without extension)",
                        max_length=255,
                    ),
                ),
                (
                    "page",
                    models.IntegerField(help_text="Page number in the source document"),
                ),
                (
                    "chunk_index",
                    models.IntegerField(help_text="Index of the chunk within the page"),
                ),
                (
                    "raw_text",
                    models.TextField(
                        help_text="Original text extracted from the source document"
                    ),
                ),
                (
                    "conversations",
                    models.JSONField(
                        default=list,
                        help_text="Structured conversation derived from the raw text.",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Flattened conversational text for fallback usage"
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        dimensions=768,
                        help_text="Vector embedding derived from the conversational text",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("conversation", "Conversation"),
                            ("behavior", "Behavior"),
                            ("content", "Content"),
                        ],
                        default="conversation",
                        help_text="Semantic type of the chunk",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["source", "page", "chunk_index"],
                "indexes": [
                    models.Index(fields=["source", "page"], name="rag_source_page_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("assistant", "Assistant"),
                            ("user", "User"),
                        ],
                        help_text="Role of the message sender",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Message text content")),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("whatsapp", "WhatsApp"),
                            ("other", "Other"),
                        ],
                        default="telegram",
                        help_text="Channel through which the message was sent",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        help_text="User profile this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
