# Generated by Django 4.2.27 on 2026-02-02 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_user_id",
                    models.CharField(
                        db_index=True,
                        help_text="Telegram user ID (unique identifier from Telegram)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User's name from Telegram (first name or full name)",
                        max_length=255,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="User's phone number (if shared)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "inferred_gender",
                    models.CharField(
                        blank=True,
                        help_text="Gender inferred from name (male/female/unknown)",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("assistant", "Assistant"),
                            ("user", "User"),
                        ],
                        help_text="Role of the message sender",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Message text content")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        help_text="User profile this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
