# Generated by Django 4.2.27 on 2026-02-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="detected_intent",
            field=models.CharField(
                blank=True,
                help_text="Primary intent/concern detected from user's first response",
                max_length=255,
                null=True,
            ),
        ),
    ]
