# Generated by Django 4.2.27 on 2026-02-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="channel",
            field=models.CharField(
                choices=[
                    ("telegram", "Telegram"),
                    ("whatsapp", "WhatsApp"),
                    ("other", "Other"),
                ],
                default="telegram",
                help_text="Channel through which the message was sent",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="telegram_user_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Telegram user ID (unique identifier from Telegram)",
                max_length=100,
                null=True,
            ),
        ),
    ]
