# Generated by Django 4.2.27 on 2026-02-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="ollama_prompt",
            field=models.JSONField(
                blank=True,
                help_text="Full Ollama prompt payload sent to LLM (for observability)",
                null=True,
            ),
        ),
    ]
