# Generated by Django 4.2.27 on 2026-02-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_message_ollama_prompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="Thematic prompt text to apply to conversations"
                    ),
                ),
            ],
        ),
    ]
