# Generated by Django 4.2.27 on 2026-02-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_message_channel_alter_profile_telegram_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="telegram_user_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Telegram user ID (unique identifier from Telegram)",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
