# Generated by Django 4.2.27 on 2026-02-02 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_profile_detected_intent"),
        ("core", "0003_alter_profile_telegram_user_id"),
    ]

    operations = []
