# Generated by Django 4.2.27 on 2026-02-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="role",
            field=models.CharField(
                choices=[
                    ("PERSON_SIMULATOR", "Person Simulator"),
                    ("BOT_SIMULATOR", "Bot Simulator"),
                ],
                default="PERSON_SIMULATOR",
                max_length=255,
            ),
        ),
    ]
