# Generated by Django 4.2.27 on 2026-02-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_merge_20260202_0127"),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pending_reset_confirmation',
            field=models.BooleanField(
                default=False,
                help_text='True if user has initiated /reset and is awaiting confirmation'
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='reset_confirmation_timestamp',
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text='Timestamp when /reset was initiated (expires after timeout)'
            ),
        ),
    ]
