# Generated by Django 4.2.27 on 2026-02-08 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_theme_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="prompt_theme",
        ),
        migrations.AddField(
            model_name="profile",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned conversation theme (temporary)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.theme",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="channel",
            field=models.CharField(
                choices=[
                    ("telegram", "Telegram"),
                    ("whatsapp", "WhatsApp"),
                    ("simulation", "Simulation"),
                    ("other", "Other"),
                ],
                default="telegram",
                help_text="Channel through which the message was sent",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="role",
            field=models.CharField(
                choices=[
                    ("PERSON_SIMULATOR", "Person Simulator"),
                    ("BOT_SIMULATOR", "Bot Simulator"),
                    ("PERSON", "Person"),
                    ("BOT", "Bot"),
                ],
                default="PERSON_SIMULATOR",
                max_length=255,
            ),
        ),
    ]
