# Generated by Django 4.2.27 on 2026-02-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_profile_prompt_theme_profile_theme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="ollama_prompt_temperature",
            field=models.FloatField(
                blank=True,
                help_text="Temperature setting used in Ollama prompt (for observability)",
                null=True,
            ),
        ),
    ]
