# Generated by Django 4.2.27 on 2026-02-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_reset_confirmation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="prompt_theme",
            field=models.CharField(
                blank=True,
                help_text="Active thematic prompt id to apply to this user's conversation",
                max_length=100,
                null=True,
            ),
        ),
    ]
