# Generated by Django 4.2.27 on 2026-02-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_message_ollama_prompt_temperature"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="exclude_from_context",
            field=models.BooleanField(
                default=False,
                help_text="If True, exclude this message from RAG and memory context",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("assistant", "Assistant"),
                    ("user", "User"),
                    ("analysis", "Analysis"),
                ],
                help_text="Role of the message sender",
                max_length=20,
            ),
        ),
    ]
