# Generated by Django 4.2.27 on 2026-02-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_message_ollama_prompt_temperature"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="welcome_message_sent",
            field=models.BooleanField(
                default=False,
                help_text="True if this message is a generated welcome message (for analytics)",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="channel",
            field=models.CharField(
                choices=[
                    ("telegram", "Telegram"),
                    ("whatsapp", "WhatsApp"),
                    ("simulation", "Simulation"),
                    ("chat", "Chat Interface"),
                    ("other", "Other"),
                ],
                default="telegram",
                help_text="Channel through which the message was sent",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("assistant", "Assistant"),
                    ("user", "User"),
                    ("analysis", "Analysis"),
                ],
                help_text="Role of the message sender",
                max_length=20,
            ),
        ),
    ]
