# Generated by Django 4.2.27 on 2026-02-04 04:27

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_profile_detected_intent"),
    ]

    operations = [
        # Enable pgvector extension
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),
        migrations.CreateModel(
            name="RagChunk",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "source",
                    models.CharField(
                        db_index=True,
                        help_text="Source document identifier (e.g., filename without extension)",
                        max_length=255,
                    ),
                ),
                (
                    "page",
                    models.IntegerField(help_text="Page number in the source document"),
                ),
                (
                    "chunk_index",
                    models.IntegerField(help_text="Index of the chunk within the page"),
                ),
                (
                    "text",
                    models.TextField(help_text="The actual text content of the chunk"),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        dimensions=768,
                        help_text="Vector embedding of the text (768-dimensional for nomic-embed-text)",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("behavior", "Behavior"), ("content", "Content")],
                        default="content",
                        help_text="Type of chunk: behavior (guidance/posture) or content (informational)",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["source", "page", "chunk_index"],
                "indexes": [
                    models.Index(fields=["source", "page"], name="rag_source_page_idx")
                ],
            },
        ),
        # Add HNSW index on embedding using cosine distance
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS core_ragchunk_embedding_idx
                ON core_ragchunk
                USING hnsw (embedding vector_cosine_ops);
            """,
            reverse_sql="DROP INDEX IF EXISTS core_ragchunk_embedding_idx;",
        ),
    ]
