# Generated by Django 4.2.27 on 2026-02-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_message_welcome_message_sent_alter_message_channel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="welcome_message_sent",
        ),
        migrations.AddField(
            model_name="profile",
            name="welcome_message_sent",
            field=models.BooleanField(
                default=False,
                help_text="True if this message is a generated welcome message (for analytics)",
            ),
        ),
    ]
