# Generated by Django 4.2.27 on 2026-02-04 04:27

from django.db import migrations, models, connection
import pgvector.django.vector


def enable_vector_extension(apps, schema_editor):
    """Enable pgvector extension only for PostgreSQL"""
    if connection.vendor == 'postgresql':
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector;")


def disable_vector_extension(apps, schema_editor):
    """Disable pgvector extension only for PostgreSQL"""
    if connection.vendor == 'postgresql':
        schema_editor.execute("DROP EXTENSION IF EXISTS vector;")


def create_vector_index(apps, schema_editor):
    """Create HNSW index only for PostgreSQL"""
    if connection.vendor == 'postgresql':
        schema_editor.execute("""
            CREATE INDEX IF NOT EXISTS core_ragchunk_embedding_idx
            ON core_ragchunk
            USING hnsw (embedding vector_cosine_ops);
        """)


def drop_vector_index(apps, schema_editor):
    """Drop HNSW index only for PostgreSQL"""
    if connection.vendor == 'postgresql':
        schema_editor.execute("DROP INDEX IF EXISTS core_ragchunk_embedding_idx;")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_profile_detected_intent"),
    ]

    operations = [
        # Enable pgvector extension (PostgreSQL only)
        migrations.RunPython(
            enable_vector_extension,
            reverse_code=disable_vector_extension,
        ),
        migrations.CreateModel(
            name="RagChunk",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "source",
                    models.CharField(
                        db_index=True,
                        help_text="Source document identifier (e.g., filename without extension)",
                        max_length=255,
                    ),
                ),
                (
                    "page",
                    models.IntegerField(help_text="Page number in the source document"),
                ),
                (
                    "chunk_index",
                    models.IntegerField(help_text="Index of the chunk within the page"),
                ),
                (
                    "text",
                    models.TextField(help_text="The actual text content of the chunk"),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        dimensions=768,
                        help_text="Vector embedding of the text (768-dimensional for nomic-embed-text)",
                        null=True,
                        blank=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("behavior", "Behavior"), ("content", "Content")],
                        default="content",
                        help_text="Type of chunk: behavior (guidance/posture) or content (informational)",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["source", "page", "chunk_index"],
                "indexes": [
                    models.Index(fields=["source", "page"], name="rag_source_page_idx")
                ],
            },
        ),
        # Add HNSW index on embedding using cosine distance (PostgreSQL only)
        migrations.RunPython(
            create_vector_index,
            reverse_code=drop_vector_index,
        ),
    ]
