# Generated by Django 4.2.27 on 2026-02-12 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_message_exclude_from_context_alter_message_role"),
        ("core", "0008_remove_message_welcome_message_sent_and_more"),
    ]

    operations = []
