from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_profile_topic_memory_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="generated_by_simulator",
            field=models.BooleanField(
                default=False,
                help_text="True when this user message was generated by simulation runtime",
            ),
        ),
    ]
