# Generated by Django 4.2.27 on 2026-02-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_message_ollama_prompt_jsonb"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="ollama_prompt_temperature",
        ),
    ]
