# Generated by Django 4.2.27 on 2026-02-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_message_ollama_prompt_temperature"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="theme",
            field=models.CharField(
                choices=[
                    ("relacionamento", "Relacionamento e família"),
                    ("financeiro", "Dinheiro e dívidas"),
                    ("vicios", "Vícios e recaídas"),
                    ("saude", "Saúde e cansaço"),
                    ("luto_perda", "Luto e perda"),
                    ("trabalho", "Trabalho e pressão"),
                    ("solidao", "Solidão"),
                    ("espiritual", "Espiritualidade"),
                    ("ansiedade", "Ansiedade"),
                    ("outros", "Outro problema"),
                ],
                db_index=True,
                default="outros",
                help_text="Classified predominant theme for this message",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="ragchunk",
            name="theme",
            field=models.CharField(
                choices=[
                    ("relacionamento", "Relacionamento e família"),
                    ("financeiro", "Dinheiro e dívidas"),
                    ("vicios", "Vícios e recaídas"),
                    ("saude", "Saúde e cansaço"),
                    ("luto_perda", "Luto e perda"),
                    ("trabalho", "Trabalho e pressão"),
                    ("solidao", "Solidão"),
                    ("espiritual", "Espiritualidade"),
                    ("ansiedade", "Ansiedade"),
                    ("outros", "Outro problema"),
                ],
                db_index=True,
                default="outros",
                help_text="Theme used to constrain RAG retrieval",
                max_length=50,
            ),
        ),
    ]
