# Generated by Django 4.2.27 on 2026-02-17 00:00

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_message_ragchunk_theme"),
    ]

    operations = [
        migrations.CreateModel(
            name="BibleTextFlat",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("translation", models.CharField(max_length=50)),
                ("testament", models.CharField(max_length=2)),
                ("book", models.CharField(max_length=100)),
                ("book_order", models.IntegerField()),
                ("chapter", models.IntegerField()),
                ("verse", models.IntegerField()),
                ("reference", models.CharField(max_length=30)),
                ("text", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=768)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("relacionamento", "Relacionamento e família"),
                            ("financeiro", "Dinheiro e dívidas"),
                            ("vicios", "Vícios e recaídas"),
                            ("saude", "Saúde e cansaço"),
                            ("luto_perda", "Luto e perda"),
                            ("trabalho", "Trabalho e pressão"),
                            ("solidao", "Solidão"),
                            ("espiritual", "Espiritualidade"),
                            ("ansiedade", "Ansiedade"),
                            ("outros", "Outro problema"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["book", "chapter", "verse"], name="bible_bcv_idx"
                    ),
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="bible_embedding_hnsw_idx",
                        opclasses=["vector_cosine_ops"],
                    ),
                ],
            },
        ),
    ]
