# Generated by Django 4.2.27 on 2026-02-17

import django.db.models.deletion
from django.db import migrations, models

THEME_LABELS = {
    "relacionamento": "Relacionamento e família",
    "financeiro": "Dinheiro e dívidas",
    "vicios": "Vícios e recaídas",
    "saude": "Saúde e cansaço",
    "luto_perda": "Luto e perda",
    "trabalho": "Trabalho e pressão",
    "solidao": "Solidão",
    "espiritual": "Espiritualidade",
    "ansiedade": "Ansiedade",
    "outros": "Outro problema",
}


def _seed_theme_v2(apps, schema_editor):
    ThemeV2 = apps.get_model("core", "ThemeV2")
    Profile = apps.get_model("core", "Profile")
    Message = apps.get_model("core", "Message")
    RagChunk = apps.get_model("core", "RagChunk")
    BibleTextFlat = apps.get_model("core", "BibleTextFlat")

    theme_ids = set(THEME_LABELS.keys())

    for value in Profile.objects.exclude(theme__isnull=True).values_list(
        "theme_id", flat=True
    ):
        if value:
            theme_ids.add(value)
    for value in Message.objects.values_list("theme", flat=True):
        if value:
            theme_ids.add(value)
    for value in RagChunk.objects.values_list("theme", flat=True):
        if value:
            theme_ids.add(value)
    for value in BibleTextFlat.objects.values_list("theme", flat=True):
        if value:
            theme_ids.add(value)

    for theme_id in sorted(theme_ids):
        theme_name = THEME_LABELS.get(theme_id, theme_id)
        ThemeV2.objects.get_or_create(
            id=theme_id,
            defaults={
                "name": theme_name,
                "prompt": f"Tema: {theme_name}",
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_bibletextflat"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThemeV2",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "prompt",
                    models.TextField(
                        help_text="Thematic prompt text to apply to conversations"
                    ),
                ),
            ],
            options={
                "db_table": "theme_v2",
                "ordering": ["name"],
            },
        ),
        migrations.RunPython(_seed_theme_v2, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="profile",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned conversation theme (temporary)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.themev2",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="theme",
            field=models.ForeignKey(
                db_column="theme",
                db_index=True,
                default="outros",
                help_text="Classified predominant theme for this message",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.themev2",
            ),
        ),
        migrations.AlterField(
            model_name="ragchunk",
            name="theme",
            field=models.ForeignKey(
                db_column="theme",
                db_index=True,
                default="outros",
                help_text="Theme used to constrain RAG retrieval",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.themev2",
            ),
        ),
        migrations.AlterField(
            model_name="bibletextflat",
            name="theme",
            field=models.ForeignKey(
                db_column="theme",
                db_index=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.themev2",
            ),
        ),
    ]
