# Generated by Django 4.2.27 on 2026-02-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_theme_v2"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Theme",
        ),
    ]
