# Generated by Django 4.2.27 on 2026-02-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_delete_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bibletextflat",
            name="translation",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
