# Generated by Django 4.2.27 on 2026-02-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_bibletextflat_translation"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS bible_embedding_hnsw_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="bibletextflat",
            name="embedding",
            field=models.JSONField(),
        ),
    ]
