# Generated by Django 4.2.27 on 2026-02-17 00:00

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_bibletextflat_translation"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bibletextflat",
            name="bible_embedding_hnsw_idx",
        ),
        migrations.AlterField(
            model_name="bibletextflat",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=3072),
        ),
    ]
