# Generated by Django 4.2.27 on 2026-02-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_bibletextflat_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ragchunk",
            name="embedding",
            field=models.JSONField(
                help_text="Vector embedding derived from the conversational text"
            ),
        ),
    ]
