# Generated by Django 4.2.27 on 2026-02-17 00:00

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_bibletextflat_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ragchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                dimensions=3072,
                help_text="Vector embedding derived from the conversational text",
            ),
        ),
    ]
