# Generated by Django 4.2.27 on 2026-02-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_ragchunk_embedding"),
    ]

    operations = [
        migrations.RenameField(
            model_name="themev2",
            old_name="prompt",
            new_name="meta_prompt",
        ),
        migrations.AddField(
            model_name="themev2",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="themev2",
            name="improvement",
            field=models.TextField(blank=True, null=True),
        ),
    ]
