# Generated by Django 4.2.27 on 2026-02-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_themev2_meta_prompt_score_improvement"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="block_root",
            field=models.ForeignKey(
                blank=True,
                help_text="First message of the regeneration block this message belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="block_messages",
                to="core.message",
            ),
        ),
    ]
