# Generated by Django 4.2.27 on 2026-02-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_message_block_root"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="score",
            field=models.FloatField(
                blank=True,
                db_index=True,
                help_text="Evaluation score for assistant messages (0-10)",
                null=True,
            ),
        ),
    ]
