# Generated by Django 4.2.27 on 2026-02-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_remove_prompt_models_from_core_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="bot_mode",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Conversation runtime mode used to generate assistant message",
                max_length=40,
                null=True,
            ),
        ),
    ]
