# Generated by Django 4.2.27 on 2026-02-20 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_profile_simulated_behavior"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exported_at", models.DateTimeField(auto_now_add=True)),
                ("approved", models.BooleanField(default=False)),
                (
                    "original_text",
                    models.TextField(
                        help_text="Original source excerpt (user question + assistant answer)"
                    ),
                ),
                (
                    "adapted_text",
                    models.TextField(
                        help_text="Adapted social media text generated by LLM"
                    ),
                ),
                (
                    "image_summary",
                    models.TextField(
                        help_text="Short summary intended to be fixed on top of the image"
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="Relevance score for social media usage (0-10)",
                        null=True,
                    ),
                ),
                (
                    "is_religious",
                    models.BooleanField(
                        default=False,
                        help_text="True when excerpt has explicit religious context",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("liked", "Liked"),
                            ("used", "Used"),
                            ("doesnt_like", "Doesn't like"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "original_message",
                    models.OneToOneField(
                        help_text="Assistant message used as source for this social media export",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_export",
                        to="core.message",
                    ),
                ),
            ],
            options={
                "db_table": "socialmediaexport",
                "ordering": ["-exported_at"],
            },
        ),
    ]
