# Generated by Django 4.2.27 on 2026-02-20 13:55

from django.db import migrations, models


def rename_used_status_to_approved(apps, schema_editor):
    SocialMediaExport = apps.get_model("core", "SocialMediaExport")
    SocialMediaExport.objects.filter(status="used").update(status="approved")


def rename_approved_status_to_used(apps, schema_editor):
    SocialMediaExport = apps.get_model("core", "SocialMediaExport")
    SocialMediaExport.objects.filter(status="approved").update(status="used")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_socialmediaexport_religous_reference"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="socialmediaexport",
            options={"ordering": ["-id"]},
        ),
        migrations.RemoveField(
            model_name="socialmediaexport",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="socialmediaexport",
            name="exported_at",
        ),
        migrations.RunPython(
            rename_used_status_to_approved,
            reverse_code=rename_approved_status_to_used,
        ),
        migrations.AlterField(
            model_name="socialmediaexport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("liked", "Liked"),
                    ("approved", "Approved"),
                    ("doesnt_like", "Doesn't like"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
