# Generated by Django 4.2.27 on 2026-02-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_alter_socialmediaexport_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediaexport",
            name="generated_image",
            field=models.ImageField(
                blank=True,
                help_text="Generated social media image file",
                null=True,
                upload_to="social_media_exports/",
            ),
        ),
    ]
