# Generated by Django 4.2.27 on 2026-02-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_socialmediaexport_generated_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediaexport",
            name="image_generation_usage",
            field=models.JSONField(
                blank=True,
                help_text="OpenAI image generation usage payload with estimated USD cost",
                null=True,
            ),
        ),
    ]
