# Generated by Django 4.2.27 on 2026-02-21 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_socialmediaexport_image_generation_usage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RagChunk",
        ),
        migrations.DeleteModel(
            name="BibleTextFlat",
        ),
    ]
