# Generated by Django 4.2.27 on 2026-02-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptcomponentversion",
            name="improvement",
            field=models.TextField(
                blank=True,
                help_text="Short recommendation to improve next generation round",
            ),
        ),
    ]
