# Generated by Django 4.2.27 on 2026-02-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0002_promptcomponentversion_improvement"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="promptreleaseitem",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="promptreleaseitem",
            name="component",
        ),
        migrations.RemoveField(
            model_name="promptreleaseitem",
            name="release",
        ),
        migrations.RemoveField(
            model_name="promptreleaseitem",
            name="version",
        ),
        migrations.RemoveField(
            model_name="promptversionproposal",
            name="based_on",
        ),
        migrations.RemoveField(
            model_name="promptversionproposal",
            name="component",
        ),
        migrations.DeleteModel(
            name="PromptRelease",
        ),
        migrations.DeleteModel(
            name="PromptReleaseItem",
        ),
        migrations.DeleteModel(
            name="PromptVersionProposal",
        ),
    ]
